### ISSUE TITLE
`sharedApplication` is unavailable in App Extensions

### ISSUE THREAD

**Issue by romaincointepas** [CooperRS/RMDateSelectionViewController#49]
The common way to make this works is to check for a macro `APP_EXTENSION=1` defined in extension targets and encapsulate sharedApplication calls in this condition.

I notice that all the call are for either status bar or orientation, which are pretty useless in app extensions (Apple messed up on this).

Potentially helpful:
http://stackoverflow.com/questions/25462091/get-device-current-orientation-app-extension
http://stackoverflow.com/questions/25179411/how-to-know-current-interfaceorientation-in-extension-of-ios-8

**Comment by CooperRS** [comment]
Most of the UIApplication calls are needed because of my UIWindow based approach. In particular, I need to know the exact orientation of the device (difference between landscape left and right and portrait and portrait up side down important) as I need to rotate the content of the UIWindow myself.

But RMDateSelectionViewController in its current state is incompatible with App Extensions anyways (see #50). So I'll close this ticket and create a new one regarding the incompatibility ;)..
