### ISSUE TITLE
Not showing when calling .show() in App Extension

### ISSUE THREAD

**Issue by romaincointepas** [CooperRS/RMDateSelectionViewController#50]
```
let dateSelectionViewController = RMDateSelectionViewController.dateSelectionController()
dateSelectionViewController.show()
```

will work perfectly inside an app, but will not show the controller inside an app extension.

**Comment by CooperRS** [comment]
Did you replace all UIApplication called by UIDevice calls to be able to compile RMDateSelectionViewController in an extension?

**Comment by CooperRS** [comment]
OK, found the problem: RMDateSelectionViewController is not showing, because App Extensions are not allowed to present new UIWindows.

On Ipads you may want to give showFromViewController a try. On the iPhone I disabled this method, because presenting RMDateSelectionViewController on top of an UINavigationController did not disable the "swipe back"-gesture.

Basically, relying on UIWindows makes RMDateSelectionViewController incompatible with App Extensions. Unfortunately :/...

**Comment by CooperRS** [comment]
Created a new ticket regarding the incompatibility of RMDateSelectionViewController with App Extensions (see #51). I'll close this one...
