### ISSUE TITLE
while scrolling

### ISSUE THREAD

**Issue by saqibilyas78** [CooperRS/RMDateSelectionViewController#67]
Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'

**Comment by liuyan3176** [comment]
Also meet this problem...
Please help us

**Comment by CooperRS** [comment]
Can you give me a demo project where the issue is reproducable? Because I haven't seen the issue before?

Also: Can you provide more infos like Stack trace, devices the issue occurs on, the operating system and so on...

Best regards,
Roland :)

**Comment by liuyan3176** [comment]
@CooperRS  the crash log is in the following
<UIVisualEffectView 0x1699cd50> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.
*** Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [nan nan]'
*** First throw call stack:
(0x2ae1b45f 0x38cf1c8b 0x2ae1b3a5 0x2dd53a9b 0x2dd5399f 0x11c54e7 0x2dd53937 0x2e7b947b 0x2e7b94eb 0x2dd5720d 0x2e347f77 0xe03ed 0x2e604c5d 0x2e3b1bd9 0x2e32ddd7 0x2ade1ffd 0x2addf6bb 0x2addfac3 0x2ad2d3b1 0x2ad2d1c3 0x3235a201 0x2e39743d 0xff2cd 0x3927daaf)
libc++abi.dylib: terminating with uncaught exception of type NSException
-----------------------------
This crash I meet in many XXDatePicker demo,but just appear in my iPhone 5C(iOS8.2) ,when I use iPhone5S (iOS 9.1) or iPhone6+ (iOS 9.2), this issue was disappeared.

**Comment by CooperRS** [comment]
Hey!

> < UIVisualEffectView 0x1699cd50 > is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.

This part is just a warning and should not produce any crashes.

For the actual crash: Unfortunately, I don't have a way to reproduce it :/. Can you provide me a demo project which can be used to reproduce the crash?

Best regards,
Roland

**Comment by liuyan3176** [comment]
@CooperRS Hi!

Sorry I can't provide you the problem project...cause this bug just occur in my company's project,when I create a new project and use the datePicker,the crash was never occur....

And just in that project,I even can not use the UIDatePicker（just in my iPhone5C iOS8.2,and setDatePickerMode:UIDatePickerModeDateAndTime or xx.datePickerMode=UIDatePickerModeDateAndTime）

Because my company's project can not run in the simulator,so I never test in that environment.

I guess my Xcode setting may bring this bug,or just occur in some special environment.I will test later and communicate you if I find something useful.
